
version: "3.3"
services:
  web:
    image: php:apache
    volumes:
      - ./DMZ/Web/index.html:/var/www/html/index.html
      - ./DMZ/Web/index.html:/var/www/www.l1-3.ephec-ti.be/index.html
      - ./DMZ/Web/index.php:/var/www/b2b.l1-3.ephec-ti.be/index.html
      - ./DMZ/Web/b2b.l2-2.ephec-ti.be.conf:/etc/apache2/sites-available/b2b.l2-2.ephec-ti.be.conf
      - ./DMZ/Web/www.l2-2.ephec-ti.be.conf:/etc/apache2/sites-available/www.l2-2.ephec-ti.be.conf
    # links:
    #   - db:database
    ports:
      - 80:80
    networks:
      dmz_net:
        ipv4_address: 192.168.0.6
    container_name: web
  # db:
  #   image: mysql:5.7
  #   expose:
  #     - 3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: database
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - ./trusted-zone/DB:/var/lib/mysql
  #   networks:
  #     dmz_net:
  #       ipv4_address: 192.168.0.7
  #   container_name: db
  dns:
    image: ubuntu/bind9
    expose:
      - 53/udp
      - 53/tcp
    volumes:
      - ./DMZ/DNS/named.conf:/etc/bind/named.conf
      - ./DMZ/DNS/db.l1-3.ephec-ti.be:/etc/bind/db.l1-3.ephec-ti.be
    networks:
      dmz_net:
        ipv4_address: 192.168.0.2
    command: named -g
    container_name: dns
    deploy:
     # If the container Exit docker try to restart it 20s after and retry each minute
     restart_policy:
       condition: any
       delay: 20s
       window: 60s

  user1:
    image: ubuntu
    networks:
      dmz_net:
        ipv4_address: 192.168.0.3
    command: sleep infinity
    container_name: user1

networks:
  dmz_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  trusted_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
