
version: "3.3"
services:
  # DMZ
  soa-externe:
    build: ./DMZ/DNS
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./DMZ/DNS/db.l1-3.ephec-ti.be:/etc/bind/db.l1-3.ephec-ti.be
      - ./DMZ/DNS/named.conf:/etc/bind/named.conf
      - ./DMZ/DNS/db.164.92.131:/etc/bind/db.164.92.131
    command: named -g
    container_name: soa-externe
    networks:
      DMZ_NET:
        ipv4_address: 172.16.0.2

  web:
    build: ./DMZ/Web
    volumes:
      - ./DMZ/Web/default/index.html:/var/www/html/index.html
      - ./DMZ/Web/www.html:/var/www/www.l1-3.ephec-ti.be/index.html
      - ./DMZ/Web/b2b.php:/var/www/b2b.l1-3.ephec-ti.be/index.php
      - ./DMZ/Web/b2b.l1-3.ephec-ti.be.conf:/etc/apache2/sites-available/b2b.l1-3.ephec-ti.be.conf
      - ./DMZ/Web/www.l1-3.ephec-ti.be.conf:/etc/apache2/sites-available/www.l1-3.ephec-ti.be.conf
    links:
      - db:database
    ports:
      - 80:80
      - 443:443
    container_name: web
    command: bash -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && a2ensite b2b.l1-3.ephec-ti.be.conf && a2ensite www.l1-3.ephec-ti.be.conf && a2enmod ssl && service apache2 start && tail -f /dev/null"
    networks:
      DMZ_NET:
        ipv4_address: 172.16.0.3

  mail:
    build: ./DMZ/Mail
    ports:
      - "25:25"   # SMTP
      - 110:110 # IMAP
      - 143:143 # POP
      - 465:465
      - 587:587
      - 993:993
      - 995:995
    command: bash -c "postfix start && dovecot && tail -f /dev/null" 
    volumes:
      - ./DMZ/Mail/mailbox:/var/mail
    networks:
      DMZ_NET:
        ipv4_address: 172.16.0.4
    container_name: mail


  db:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: woodytoys
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 0.50
    #       memory: 100M
    volumes:
      - ./db-data:/var/lib/mysql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        #- my-datavolume:/var/lib/mysql
      # - ./database/my.cnf:/etc/mysql/my.cnf
    networks:
      DB_NET:
        ipv4_address: 10.2.0.2
    container_name: db


  # Trusted zone
  soa-interne:
    build: trusted-zone/DNS
    expose:
      - 53/udp
      - 53/tcp
    volumes:
      - ./trusted-zone/DNS/named.conf:/etc/bind/named.conf
      - ./trusted-zone/DNS/db.10.0.0:/etc/bind/db.10.0.0
    command: named -g
    container_name: soa-interne
    networks:
      SECURED_NET:
        ipv4_address: 10.0.0.2
  erp:
    build: trusted-zone/Web
    volumes:
      - ./trusted-zone/Web/default/index.html:/var/www/html/index.html
      - ./trusted-zone/Web/intranet.php:/var/www/intranet.woodytoys.lab/index.php
      - ./trusted-zone/Web/intranet.woodytoys.lab.conf:/etc/apache2/sites-available/intranet.woodytoys.lab.conf
    links:
      - db:database
    expose:
      - 80
      - 443
    container_name: erp
    command: bash -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && a2ensite intranet.woodytoys.lab.conf && a2enmod ssl && service apache2 start && tail -f /dev/null"
    networks:
      SECURED_NET:
        ipv4_address: 10.0.0.3



  # Internal network
  atelier:
    image: alpine
    command: ash -c "apk update && apk upgrade && apk add lynx bind-tools busybox-extras mysql && echo -e 'search ephec.be\nnameserver 10.0.0.2\noptions edns0 trust-ad ndots:0' > /etc/resolv.conf && tail -f /dev/null"
    container_name: atelier
    networks:
      USER_NET:
        ipv4_address: 10.1.0.2
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    networks:
      USER_NET:
        ipv4_address: 10.1.0.50


networks:
  DMZ_NET:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  DB_NET:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
  SECURED_NET:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  USER_NET:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

# apk update
# apk add bind-tools vim
# vim /etc/resolv.conf
