
version: "3.3"
services:
  # web:
  #   image: nginx:alpine
  #   links:
  #     - db:database
  #   ports:
  #     - 80:80
  #   networks:
  #     - private-net
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: database
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - private-net
  dns:
    image: ubuntu/bind9
    expose:
      - 53/udp
      - 53/tcp
    volumes:
      - ./DNS/named.conf:/etc/bind/named.conf
      - ./DNS/db.l1-3.ephec-ti.be:/etc/bind/db.l1-3.ephec-ti.be
    networks:
      dmz_net:
        ipv4_address: 192.168.0.2
    command: named -g
    container_name: dns
    deploy:
     # If the container Exit docker try to restart it 20s after and retry each minute
     restart_policy:
       condition: any
       delay: 20s
       window: 60s

  user1:
    image: ubuntu
    networks:
      dmz_net:
        ipv4_address: 192.168.0.3
    command: sleep infinity
    container_name: user1

networks:
  dmz_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  trusted_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
  container_name: 'networks'