
version: "3.3"
services:
  # DMZ
  user2:
    image: alpine
    command: ash -c "apk update && apk upgrade && apk add net-tools && tail -f /dev/null"
    container_name: user2
    privileged: true
    networks:
      dmz_net:
        ipv4_address: 10.0.0.2

  # Internal network
  user1:
    image: alpine
    command: ash -c "apk update && apk upgrade && apk add net-tools && tail -f /dev/null"
    container_name: user1
    privileged: true
    networks:
      user_net:
        ipv4_address: 192.168.0.2
  
  router:
    image: alpine
    command: ash -c "apk update && apk upgrade && apk add net-tools && tail -f /dev/null"
    container_name: router
    networks:
      dmz_net:
        ipv4_address: 10.0.0.254
      user_net:
        ipv4_address: 192.168.0.254


networks:
  dmz_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  user_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24

# apk update
# apk add bind-tools vim
# vim /etc/resolv.conf
