
version: "3.3"
services:
  # DMZ
  web:
    image: php:7.2-apache
    volumes:
      - ./DMZ/Web/default/index.html:/var/www/html/index.html
      - ./DMZ/Web/index.html:/var/www/www.woodytoys.be/index.html
      - ./DMZ/Web/index.php:/var/www/b2b.woodytoys.be/index.php
      - ./DMZ/Web/b2b.woodytoys.be.conf:/etc/apache2/sites-available/b2b.woodytoys.be.conf
      - ./DMZ/Web/www.woodytoys.be.conf:/etc/apache2/sites-available/www.woodytoys.be.conf
    links:
      - db:database
    expose:
      - 80
      - 443
    container_name: web
    command: bash -c "apt update && apt upgrade -y && docker-php-ext-install mysqli && docker-php-ext-enable mysqli && a2ensite b2b.woodytoys.be.conf && a2ensite www.woodytoys.be.conf && service apache2 start && tail -f /dev/null"
    networks:
      dmz_net:
        ipv4_address: 10.0.0.2
  db:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: woodytoys
      MYSQL_USER: b2b
      MYSQL_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      dmz_net:
        ipv4_address: 10.0.0.6
    container_name: db

  # Trusted zone
  soa-interne:
    image: ubuntu/bind9
    expose:
      - 53/udp
      - 53/tcp
    volumes:
      - ./trusted-zone/DNS/named.conf:/etc/bind/named.conf
      - ./trusted-zone/DNS/db.woodytoys.be:/etc/bind/db.woodytoys.be
      - ./trusted-zone/DNS/db.woodytoys.lab:/etc/bind/db.woodytoys.lab
    command: named -g
    container_name: soa-interne
    networks:
      dmz_net:
        ipv4_address: 10.0.0.4

  # Internal network
  user1:
    image: alpine
    command: sleep infinity
    container_name: user1
    networks:
      dmz_net:
        ipv4_address: 10.0.0.5

networks:
  dmz_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

# apk update
# apk add bind-tools vim
# vim /etc/resolv.conf
